CREATE TABLE "icon_generations" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "icon_generations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uuid" varchar(255) NOT NULL,
	"user_uuid" varchar(255) NOT NULL,
	"prompt" text NOT NULL,
	"style" varchar(50) NOT NULL,
	"format" varchar(10) NOT NULL,
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"provider" varchar(100) DEFAULT 'freepik' NOT NULL,
	"freepik_task_id" varchar(255),
	"num_inference_steps" integer DEFAULT 20,
	"guidance_scale" integer DEFAULT 7,
	"webhook_url" varchar(500),
	"r2_key" varchar(500),
	"r2_url" varchar(500),
	"original_url" varchar(500),
	"file_size" integer,
	"credits_cost" integer DEFAULT 1 NOT NULL,
	"generation_time" integer,
	"error_message" text,
	"created_at" timestamp with time zone,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	CONSTRAINT "icon_generations_uuid_unique" UNIQUE("uuid")
);
